"""Pandas-backed draft inference and reproducible script helpers."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

from mplgallery.core.models import MatplotlibFigureAttributes, RedrawMetadata, SeriesStyle
from mplgallery.core.renderer import DEFAULT_COLOR_CYCLE

GENERATED_INDEX_COLUMN = "mplgallery_index"


@dataclass(frozen=True)
class PandasDraft:
    redraw: RedrawMetadata
    plot_frame: pd.DataFrame
    pandas_kind: str


def infer_pandas_draft(csv_path: Path, frame: pd.DataFrame) -> PandasDraft | None:
    """Infer a useful first-pass pandas plot from a CSV-shaped frame."""
    if frame.empty and not frame.columns.size:
        return None

    plot_frame = frame.copy()
    numeric_columns = _numeric_columns(plot_frame)
    if not numeric_columns:
        return None

    categorical_columns = [str(column) for column in plot_frame.columns if str(column) not in numeric_columns]
    title = _human_title(csv_path.stem)
    if categorical_columns and len(numeric_columns) == 1:
        x_column = categorical_columns[0]
        y_columns = [numeric_columns[0]]
        kind = "bar"
        pandas_kind = "bar"
    elif len(numeric_columns) >= 2:
        x_column = numeric_columns[0]
        y_columns = numeric_columns[1:5]
        kind = "line"
        pandas_kind = "line"
    else:
        x_column = GENERATED_INDEX_COLUMN
        y_columns = [numeric_columns[0]]
        plot_frame.insert(0, x_column, range(len(plot_frame)))
        kind = "line"
        pandas_kind = "line"

    return PandasDraft(
        redraw=RedrawMetadata(
            kind=kind,
            x=x_column,
            y=y_columns,
            title=title,
            xlabel=_human_title(x_column),
            ylabel=_human_title(y_columns[0]) if len(y_columns) == 1 else "Value",
            grid=True,
            figure=MatplotlibFigureAttributes(width_inches=7.0, height_inches=4.5, dpi=150),
            series=_draft_series(kind, y_columns),
        ),
        plot_frame=plot_frame,
        pandas_kind=pandas_kind,
    )


def pandas_kind_for_redraw(redraw: RedrawMetadata) -> str:
    """Map editable Matplotlib kinds to the closest pandas plotting kind."""
    if redraw.kind in {"line", "scatter", "bar", "barh", "area", "hist"}:
        return redraw.kind
    if redraw.kind == "step":
        return "line"
    return "line"


def render_pandas_draft_figure(
    frame: pd.DataFrame,
    redraw: RedrawMetadata,
    *,
    fallback_title: str,
) -> tuple[plt.Figure, plt.Axes]:
    """Render a draft with pandas plotting, then apply Matplotlib metadata."""
    if frame.empty:
        raise ValueError("CSV data is empty")

    figure = redraw.figure
    fig, ax = plt.subplots(
        figsize=(figure.width_inches, figure.height_inches),
        dpi=figure.dpi,
        facecolor=figure.facecolor,
        constrained_layout=bool(figure.constrained_layout) if figure.constrained_layout is not None else False,
    )
    try:
        x_column = redraw.x or str(frame.columns[0])
        series = _series_from_redraw(frame, redraw, x_column)
        if not series:
            raise ValueError("No y columns configured for pandas draft")
        _plot_with_pandas(frame, redraw, ax, x_column, series)
        _apply_matplotlib_metadata(ax, redraw, x_column, series, fallback_title=fallback_title)
    except Exception:
        plt.close(fig)
        raise
    return fig, ax


def generated_script_text(recipe_payload: dict[str, object], plot_ready_path: Path, cache_path: Path) -> str:
    """Create a pandas-first render script for a recipe."""
    lines = [
        '"""Reproducible draft render script generated by MPLGallery."""',
        "",
        "from __future__ import annotations",
        "",
        "from pathlib import Path",
        "",
        "import matplotlib.pyplot as plt",
        "import pandas as pd",
        "",
        "",
        "ROOT = Path(__file__).resolve().parents[2]",
        f"PLOT_READY_CSV = ROOT / {plot_ready_path.as_posix()!r}",
        f"CACHE_PATH = ROOT / {cache_path.as_posix()!r}",
        f"REDRAW = {recipe_payload!r}",
        "",
        "",
        "def axis_label(label: str, unit: str | None) -> str:",
        "    if not unit:",
        "        return label",
        "    if label.endswith(unit):",
        "        return label",
        "    return f'{label} ({unit})'",
        "",
        "",
        "def main() -> None:",
        "    frame = pd.read_csv(PLOT_READY_CSV)",
        "    kind = REDRAW.get('kind', 'line')",
        "    pandas_kind = kind if kind in {'line', 'scatter', 'bar', 'barh', 'area', 'hist'} else 'line'",
        "    x = REDRAW.get('x') or frame.columns[0]",
        "    series = REDRAW.get('series') or [{'y': column} for column in REDRAW.get('y', [])]",
        "    if not series:",
        "        series = [{'y': column} for column in frame.columns if column != x]",
        "    y_columns = [series_item['y'] for series_item in series]",
        "    figure = REDRAW.get('figure', {})",
        "    common = {",
        "        'figsize': (figure.get('width_inches', 7.0), figure.get('height_inches', 4.5)),",
        "    }",
        "    if pandas_kind == 'hist':",
        "        ax = frame[y_columns].plot(",
        "            kind='hist',",
        "            bins=REDRAW.get('bins') or 20,",
        "            alpha=series[0].get('alpha', 0.75),",
        "            color=series[0].get('color'),",
        "            **common,",
        "        )",
        "    elif pandas_kind == 'scatter':",
        "        first = series[0]",
        "        ax = frame.plot(",
        "            x=x,",
        "            y=first['y'],",
        "            kind='scatter',",
        "            color=first.get('color'),",
        "            alpha=first.get('alpha'),",
        "            **common,",
        "        )",
        "    else:",
        "        ax = frame.plot(",
        "            x=x,",
        "            y=y_columns,",
        "            kind=pandas_kind,",
        "            color=[item.get('color') for item in series] if pandas_kind != 'barh' else None,",
        "            alpha=series[0].get('alpha') if series else None,",
        "            **common,",
        "        )",
        "    fig = ax.get_figure()",
        "    fig.set_dpi(figure.get('dpi', 150))",
        "    for line, style in zip(ax.get_lines(), series, strict=False):",
        "        line.set_label(style.get('label') or style['y'])",
        "        if style.get('color'):",
        "            line.set_color(style['color'])",
        "        if style.get('linewidth') is not None:",
        "            line.set_linewidth(style['linewidth'])",
        "        if style.get('linestyle') is not None:",
        "            line.set_linestyle(style['linestyle'])",
        "        if style.get('marker') is not None:",
        "            line.set_marker(style['marker'])",
        "        if style.get('markersize') is not None:",
        "            line.set_markersize(style['markersize'])",
        "        if style.get('alpha') is not None:",
        "            line.set_alpha(style['alpha'])",
        "    for patch in ax.patches:",
        "        style = series[0] if series else {}",
        "        if style.get('edgecolor'):",
        "            patch.set_edgecolor(style['edgecolor'])",
        "        if style.get('hatch'):",
        "            patch.set_hatch(style['hatch'])",
        "        if style.get('alpha') is not None:",
        "            patch.set_alpha(style['alpha'])",
        "    ax.set_title(REDRAW.get('title') or CACHE_PATH.stem)",
        "    ax.set_xlabel(axis_label(REDRAW.get('xlabel') or x, REDRAW.get('xlabel_unit')))",
        "    ylabel = REDRAW.get('ylabel') or ', '.join(item.get('label') or item['y'] for item in series)",
        "    ax.set_ylabel(axis_label(ylabel, REDRAW.get('ylabel_unit')))",
        "    ax.set_xscale(REDRAW.get('xscale', 'linear'))",
        "    ax.set_yscale(REDRAW.get('yscale', 'linear'))",
        "    if REDRAW.get('xlim') is not None:",
        "        ax.set_xlim(REDRAW['xlim'])",
        "    if REDRAW.get('ylim') is not None:",
        "        ax.set_ylim(REDRAW['ylim'])",
        "    ax.grid(",
        "        bool(REDRAW.get('grid', True)),",
        "        axis=REDRAW.get('grid_axis') or 'both',",
        "        alpha=REDRAW.get('grid_alpha', 0.25),",
        "    )",
        "    if series:",
        "        ax.legend(title=REDRAW.get('legend_title') or None, loc=REDRAW.get('legend_location') or 'best')",
        "    CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)",
        "    fig.tight_layout()",
        "    fig.savefig(CACHE_PATH)",
        "    plt.close(fig)",
        "",
        "",
        "if __name__ == '__main__':",
        "    main()",
        "",
    ]
    return "\n".join(lines)


def _plot_with_pandas(
    frame: pd.DataFrame,
    redraw: RedrawMetadata,
    ax: plt.Axes,
    x_column: str,
    series: list[SeriesStyle],
) -> None:
    y_columns = [style.y for style in series]
    kind = pandas_kind_for_redraw(redraw)
    if kind == "hist":
        frame[y_columns].plot.hist(
            ax=ax,
            bins=redraw.bins or 20,
            alpha=series[0].alpha if series[0].alpha is not None else 0.75,
            color=series[0].color,
            edgecolor=series[0].edgecolor,
            legend=len(y_columns) > 1,
        )
        _apply_patch_styles(ax, series[0])
    elif kind == "scatter":
        first = series[0]
        frame.plot.scatter(
            x=x_column,
            y=first.y,
            ax=ax,
            color=first.color,
            s=(first.markersize or 6) ** 2,
            alpha=first.alpha,
            label=first.label or first.y,
        )
    else:
        kwargs: dict[str, object] = {
            "x": x_column,
            "y": y_columns,
            "kind": kind,
            "ax": ax,
            "legend": len(series) > 1 or any(style.label for style in series),
        }
        colors = [style.color for style in series if style.color]
        if colors:
            kwargs["color"] = colors if len(colors) > 1 else colors[0]
        if kind in {"bar", "barh", "area"} and series[0].alpha is not None:
            kwargs["alpha"] = series[0].alpha
        frame.plot(**kwargs)
        if kind in {"line", "area"}:
            _apply_line_styles(ax, series)
        elif kind in {"bar", "barh"}:
            _apply_patch_styles(ax, series[0])


def _apply_line_styles(ax: plt.Axes, series: list[SeriesStyle]) -> None:
    for line, style in zip(ax.get_lines(), series, strict=False):
        line.set_label(style.label or style.y)
        if style.color:
            line.set_color(style.color)
        if style.linewidth is not None:
            line.set_linewidth(style.linewidth)
        if style.linestyle is not None:
            line.set_linestyle(style.linestyle)
        if style.marker is not None:
            line.set_marker(style.marker)
        if style.markersize is not None:
            line.set_markersize(style.markersize)
        if style.alpha is not None:
            line.set_alpha(style.alpha)
        if style.zorder is not None:
            line.set_zorder(style.zorder)


def _apply_patch_styles(ax: plt.Axes, style: SeriesStyle) -> None:
    for patch in ax.patches:
        if style.edgecolor:
            patch.set_edgecolor(style.edgecolor)
        if style.linewidth is not None:
            patch.set_linewidth(style.linewidth)
        if style.hatch:
            patch.set_hatch(style.hatch)
        if style.alpha is not None:
            patch.set_alpha(style.alpha)
        if style.zorder is not None:
            patch.set_zorder(style.zorder)


def _apply_matplotlib_metadata(
    ax: plt.Axes,
    redraw: RedrawMetadata,
    x_column: str,
    series: list[SeriesStyle],
    *,
    fallback_title: str,
) -> None:
    ax.set_title(redraw.title or fallback_title)
    ax.set_xlabel(_compose_axis_label(redraw.xlabel or x_column, redraw.xlabel_unit))
    ylabel = redraw.ylabel or ", ".join(style.label or style.y for style in series)
    ax.set_ylabel(_compose_axis_label(ylabel, redraw.ylabel_unit))
    ax.set_xscale(redraw.xscale)
    ax.set_yscale(redraw.yscale)
    if redraw.xlim is not None:
        ax.set_xlim(redraw.xlim)
    if redraw.ylim is not None:
        ax.set_ylim(redraw.ylim)
    ax.grid(
        redraw.grid,
        axis=redraw.grid_axis or "both",
        alpha=redraw.grid_alpha if redraw.grid_alpha is not None else 0.25,
    )
    if len(series) > 1 or any(style.label for style in series):
        ax.legend(title=redraw.legend_title or None, loc=redraw.legend_location or "best")


def _series_from_redraw(frame: pd.DataFrame, redraw: RedrawMetadata, x_column: str) -> list[SeriesStyle]:
    if redraw.series:
        return redraw.series
    if redraw.y:
        return [SeriesStyle(y=column) for column in redraw.y]
    return [SeriesStyle(y=str(column)) for column in frame.columns if str(column) != x_column]


def _draft_series(kind: str, y_columns: list[str]) -> list[SeriesStyle]:
    return [
        SeriesStyle(
            y=column,
            label=_human_title(column),
            color=DEFAULT_COLOR_CYCLE[index % len(DEFAULT_COLOR_CYCLE)],
            linewidth=1.6,
            marker="o" if kind == "line" else None,
            markersize=4 if kind == "line" else None,
            alpha=0.9,
        )
        for index, column in enumerate(y_columns)
    ]


def _numeric_columns(frame: pd.DataFrame) -> list[str]:
    numeric: list[str] = []
    for column in frame.columns:
        values = pd.to_numeric(frame[column], errors="coerce")
        if values.notna().any():
            numeric.append(str(column))
    return numeric


def _compose_axis_label(label: str, unit: str | None) -> str:
    if not unit:
        return label
    if label.endswith(unit):
        return label
    return f"{label} ({unit})"


def _human_title(value: str) -> str:
    return value.replace("_", " ").replace("-", " ").strip().title()
